site_name: Ceph Training Document
theme: readthedocs
pages: 
 - [index.md, Home]
 - [Monitor.md, 'Ceph Monitor']
 - [Ceph_OSD.md, 'Ceph OSD']
 - [Data_Placement.md, 'Data Placement']
 - [Ceph_Client.md, 'Ceph Client']
 - [Ceph_IO.md, 'Ceph IO']
 - [FAQ.md, 'FAQ']

